# Generated by Django 2.0.1 on 2018-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='sesso',
            field=models.CharField(choices=[('MASCHIO', 'MASCHIO'), ('FEMMINA', 'FEMMINA')], default='MASCHIO', max_length=50),
        ),
    ]
