# Generated by Django 2.0.1 on 2018-09-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRI', '0003_auto_20180911_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
