# Generated by Django 2.0.1 on 2018-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRI', '0004_utente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='sesso',
            field=models.CharField(choices=[('0', '--scegli--'), ('MASCHIO', 'MASCHIO'), ('FEMMINA', 'FEMMINA'), ('ALTRO', 'Si, Grazie')], default='0', max_length=50),
        ),
    ]
