# Generated by Django 2.0.1 on 2018-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRI', '0005_auto_20180912_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('principio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='utente',
            name='passwordConfirm',
            field=models.CharField(default='', max_length=50),
        ),
    ]
